/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user + instance role context */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public-safe instance config (upload limits, handle rules, auth modes) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OIDC login (302 to the IdP) */
        get: operations["authLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC callback (verifies state, sets the __Host- session cookie, 302s to next) */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Destroy the server session + clear the cookie */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sites visible to the caller (owned or member) */
        get: operations["listSites"];
        put?: never;
        /** Create a site (empty draft, or seed via a subsequent zip import) */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /** Get one site (current handle only; old handles 404 here) */
        get: operations["getSite"];
        put?: never;
        post?: never;
        /** Soft-delete a site (owner only; 30-day grace, then reaper reclaims disk) */
        delete: operations["deleteSite"];
        options?: never;
        head?: never;
        /** Update site settings (visibility, publishMode, description, webRoot) - owner only */
        patch: operations["updateSite"];
        trace?: never;
    };
    "/api/sites/{handle}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename the handle (owner only; records a redirect; files do not move) */
        post: operations["renameSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /** List site members + roles */
        get: operations["listMembers"];
        put?: never;
        /** Add or upsert a member by email (owner only) */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member (owner only; cannot remove the sole owner) */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change a member's role (owner only) */
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/api/sites/{handle}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /** List site tokens (never returns the secret or hash) */
        get: operations["listTokens"];
        put?: never;
        /** Issue a site token (owner only; plaintext returned ONCE) */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                tokenId: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a site token (owner only) */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /** List branches (enumerated from git, not the DB) */
        get: operations["listBranches"];
        put?: never;
        /** Create a host-safe branch (feature-<user>-<slug>) from a ref */
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a branch (never published/draft) */
        delete: operations["deleteBranch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        /** List files under a directory at a branch tip or ref */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        /** Read one file; `sha` is the commit lock-token to echo as baseSha on write */
        get: operations["readFile"];
        /** Write one file with optimistic locking (baseSha REQUIRED); published not writable */
        put: operations["writeFile"];
        post?: never;
        /** Delete one file with optimistic locking */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}/import": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a zip; REPLACES the branch tree as one commit. multipart form. */
        post: operations["importZip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit ("save") the staged working set as one commit (multi-file batch) */
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote a source branch to published (direct mode) with optimistic locking */
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /** Diff two refs (or a ref vs its working tree when `to` is omitted) */
        get: operations["getDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}/log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        /** Commit history (newest first), cursor-paginated by `before` */
        get: operations["getLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{handle}/branches/{branch}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a branch to an ancestor commit's tree as a NEW forward commit */
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GitHub webhook ingress (HMAC-verified; advances published via fast-forward) */
        post: operations["githubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
         * @example expense-calc
         */
        HandleString: string;
        /**
         * @description Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
         * @example draft
         */
        BranchString: string;
        /** @description Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256). */
        Sha: string;
        /** @enum {string} */
        SiteRole: "owner" | "editor" | "viewer";
        /** @enum {string} */
        SiteVisibility: "public" | "internal" | "private";
        /** @enum {string} */
        PublishMode: "direct" | "request";
        /** @enum {string} */
        TokenScope: "read" | "write" | "publish";
        /** @enum {string} */
        WriteSource: "upload" | "editor" | "mcp" | "system";
        /** @enum {string} */
        AuthMode: "oidc" | "password" | "none";
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "unauthenticated" | "forbidden" | "validation" | "conflict" | "not_found" | "handle_taken" | "publish_conflict" | "branch_exists" | "nothing_to_commit" | "too_large" | "unsupported_media_type" | "rate_limited" | "quota_exceeded" | "internal";
                message: string;
                /** @description Code-specific structured detail (e.g. validation field, retry hint). */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ConflictEnvelope: {
            error: {
                /** @enum {string} */
                code: "conflict" | "handle_taken" | "branch_exists" | "nothing_to_commit";
                message: string;
                details: components["schemas"]["ConflictError"];
            };
        };
        /** @description Optimistic-lock conflict detail (frozen field names; CANONICAL.md §8). */
        ConflictError: {
            branch: components["schemas"]["BranchString"];
            /** @description the baseSha the caller sent */
            expected: string;
            /** @description the real current branch tip */
            actual: string;
            changedPaths?: string[];
        };
        PublishConflictEnvelope: {
            error: {
                /** @enum {string} */
                code: "publish_conflict";
                message: string;
                details: {
                    paths: string[];
                };
            };
        };
        Me: {
            user: components["schemas"]["User"];
            authMode: components["schemas"]["AuthMode"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** @description instance superuser (separate axis from site roles) */
            isAdmin: boolean;
            canCreateSites: boolean;
        };
        InstanceConfig: {
            /** Format: int64 */
            maxUploadBytes: number;
            zipMaxFiles: number;
            /** Format: int64 */
            zipMaxTotalBytes: number;
            /** Format: int64 */
            zipMaxEntryBytes?: number;
            zipMaxRatio?: number;
            allowedExtensions: string[];
            handleMinLen: number;
            handleMaxLen: number;
            reservedHandles: string[];
            /** @example hosting.example.com */
            baseDomain: string;
            authMode: components["schemas"]["AuthMode"];
            defaultPublishMode: components["schemas"]["PublishMode"];
        };
        Site: {
            /** Format: uuid */
            id: string;
            handle: components["schemas"]["HandleString"];
            /** Format: uuid */
            ownerId: string;
            visibility: components["schemas"]["SiteVisibility"];
            defaultBranch: components["schemas"]["BranchString"];
            /** @example necorox-com/expense-calc */
            githubRepo?: string | null;
            publishMode: components["schemas"]["PublishMode"];
            /** @description served subdir; empty = repo root (v1) */
            webRoot: string;
            /** @description derived: publishedSha is set */
            hasPublished: boolean;
            publishedSha?: string | null;
            /** Format: date-time */
            publishedAt?: string | null;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SiteSummary: {
            /** Format: uuid */
            id: string;
            handle: components["schemas"]["HandleString"];
            visibility: components["schemas"]["SiteVisibility"];
            defaultBranch?: components["schemas"]["BranchString"];
            publishedSha?: string | null;
            /** Format: date-time */
            publishedAt?: string | null;
            hasPublished: boolean;
            description?: string;
            /** Format: date-time */
            updatedAt: string;
            role: components["schemas"]["SiteRole"];
        };
        CreateSiteRequest: {
            handle: components["schemas"]["HandleString"];
            /** @default private */
            visibility: components["schemas"]["SiteVisibility"];
            /** @default direct */
            publishMode: components["schemas"]["PublishMode"];
            /** @default  */
            description: string;
            githubRepo?: string | null;
        };
        UpdateSiteRequest: {
            visibility?: components["schemas"]["SiteVisibility"];
            publishMode?: components["schemas"]["PublishMode"];
            description?: string;
            webRoot?: string;
            githubRepo?: string | null;
        };
        Member: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["SiteRole"];
            /** Format: date-time */
            createdAt?: string;
        };
        TokenSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description first 12 chars of the plaintext */
            tokenPrefix: string;
            scopes: components["schemas"]["TokenScope"][];
            canCreateSites: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
        };
        CreateTokenRequest: {
            name: string;
            scopes: components["schemas"]["TokenScope"][];
            /** @default false */
            canCreateSites: boolean;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        CreatedToken: components["schemas"]["TokenSummary"] & {
            /** @description The plaintext "kotoji_pat_..." secret. Shown ONCE; never returned again. */
            token: string;
        };
        Branch: {
            name: components["schemas"]["BranchString"];
            headSha: components["schemas"]["Sha"];
            isPublished: boolean;
            lastCommit?: components["schemas"]["CommitInfo"];
            /** @description host label fragment: "{handle}" for published, "{handle}--{branch}" otherwise */
            previewSubdomain: string;
        };
        FileEntry: {
            /** @description repo-relative, forward slashes, no leading / */
            path: string;
            name: string;
            isDir: boolean;
            /** Format: int64 */
            size: number;
            /** @example 100644 */
            mode: string;
        };
        FileListing: {
            branch: components["schemas"]["BranchString"];
            /** @description the resolved SHA the listing reflects */
            ref: components["schemas"]["Sha"];
            files: components["schemas"]["FileEntry"][];
        };
        FileContent: {
            path: string;
            /** @description COMMIT SHA the content was read at - echo as baseSha on write (the lock token). */
            sha: components["schemas"]["Sha"];
            blobSha: string;
            /** @enum {string} */
            encoding: "utf-8" | "base64";
            /** @description utf-8 text or base64 per encoding */
            content: string;
            /** Format: int64 */
            size: number;
            isBinary: boolean;
            /** @default false */
            truncated: boolean;
        };
        WriteFileRequest: {
            path: string;
            content: string;
            /**
             * @default utf-8
             * @enum {string}
             */
            encoding: "utf-8" | "base64";
            /** @description REQUIRED commit SHA the edit is based on. Empty/stale => 409 conflict. */
            baseSha: string;
            /** @default true */
            commit: boolean;
            message?: string;
        };
        WriteResult: {
            path: string;
            branch: components["schemas"]["BranchString"];
            committed: boolean;
            /** @description new tip; becomes the next baseSha */
            commit: components["schemas"]["Sha"];
            blobSha?: string;
            /** @description mirror-push to GitHub succeeded (best-effort) */
            pushed: boolean;
            bytesWritten?: number;
            filesChanged?: number;
            /** @default false */
            noOp: boolean;
            warnings?: string[];
        };
        CommitInfo: {
            sha: components["schemas"]["Sha"];
            shortSha: string;
            message: string;
            authorName: string;
            authorEmail: string;
            /** Format: date-time */
            committed: string;
            parents?: string[];
            via: components["schemas"]["WriteSource"];
        };
        CommitRequest: {
            /** @description REQUIRED optimistic lock; current branch tip */
            baseSha: string;
            message?: string;
        };
        PublishRequest: {
            /** @default draft */
            from: components["schemas"]["BranchString"];
            /** @description REQUIRED tip of `from` the publish is intended for */
            baseSha: string;
            message?: string;
        };
        PublishResult: {
            publishedCommit: components["schemas"]["Sha"];
            /** Format: uri */
            publishedUrl?: string;
            from: components["schemas"]["BranchString"];
            fromCommit: components["schemas"]["Sha"];
            pushed: boolean;
            warnings?: string[];
        };
        DiffResult: {
            fromSha: string;
            toSha: string;
            files: components["schemas"]["FileDiff"][];
            /** @default false */
            truncated: boolean;
        };
        FileDiff: {
            path: string;
            /** @description set on rename */
            oldPath?: string | null;
            /** @enum {string} */
            status: "added" | "modified" | "deleted" | "renamed";
            additions: number;
            deletions: number;
            isBinary: boolean;
            /** @description empty if binary or name-status mode */
            unifiedPatch?: string;
        };
        LogResult: {
            branch: components["schemas"]["BranchString"];
            commits: components["schemas"]["CommitInfo"][];
            /** @description cursor for the next page; null at end */
            nextBefore?: string | null;
        };
        RollbackRequest: {
            /** @description ancestor commit on this branch whose tree to restore (non-ancestor => 404) */
            toSha: string;
            /** @description REQUIRED current branch tip (optimistic lock) */
            baseSha: string;
            message?: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Optimistic-lock conflict, handle taken, or similar 409 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConflictEnvelope"];
            };
        };
        /** @description Payload/zip too large */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Disallowed file extension / media type */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed (handle/path/branch/baseSha rules) */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Handle: components["schemas"]["HandleString"];
        Branch: components["schemas"]["BranchString"];
        UserId: string;
        TokenId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceConfig"];
                };
            };
        };
    };
    authLogin: {
        parameters: {
            query?: {
                /** @description Post-login redirect target (validated server-side). */
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the OIDC authorization endpoint */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login complete; session cookie set */
            302: {
                headers: {
                    Location?: string;
                    /** @description __Host-kotoji_session */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sites: components["schemas"]["SiteSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSiteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller lacks can_create_sites or exceeds the site quota */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSiteRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    renameSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    newHandle: components["schemas"]["HandleString"];
                };
            };
        };
        responses: {
            /** @description Renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["Member"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["SiteRole"];
                };
            };
        };
        responses: {
            /** @description Member added/updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["SiteRole"];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tokens: components["schemas"]["TokenSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description Created; plaintext shown once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                tokenId: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listBranches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        branches: components["schemas"]["Branch"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: components["schemas"]["BranchString"];
                    /** @description source branch name or SHA */
                    from: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listFiles: {
        parameters: {
            query?: {
                dir?: string;
                /** @description commit SHA; default = branch tip */
                ref?: string;
                recursive?: boolean;
            };
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListing"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    readFile: {
        parameters: {
            query: {
                path: string;
                ref?: string;
            };
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    writeFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteFileRequest"];
            };
        };
        responses: {
            /** @description Written (and committed unless commit=false) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteFile: {
        parameters: {
            query: {
                path: string;
                baseSha: string;
                message?: string;
            };
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (new commit) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    importZip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description the .zip archive
                     */
                    file: string;
                    /** @description REQUIRED unless the branch has no commits yet (initial seed) */
                    baseSha?: string;
                    message?: string;
                };
            };
        };
        responses: {
            /** @description Imported (new commit) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Stale base SHA (conflict) or publish merge conflict (publish_conflict) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictEnvelope"] | components["schemas"]["PublishConflictEnvelope"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getDiff: {
        parameters: {
            query: {
                from: string;
                /** @description omit => working tree of from's branch */
                to?: string;
                path?: string;
                contextLines?: number;
                nameStatus?: boolean;
            };
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getLog: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor SHA (exclusive) */
                before?: string;
                path?: string;
            };
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["Handle"];
                branch: components["parameters"]["Branch"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            /** @description Rolled back (new commit) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    githubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Hub-Signature-256": string;
                "X-GitHub-Event": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted (work may continue async) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
