-- sites.sql — site lifecycle + handle resolution queries.
-- Column names match the 0001_init `sites` / `handle_redirects` DDL exactly.

-- name: CreateSite :one
-- Create a site (UUID generated by DB). Runs in the SAME tx as CreateOwnerMembership
-- and the SiteService git-init (Phase 2). The handle is pre-validated + collision-checked
-- (sites/redirects/reserved) by the app before this call; the DB UNIQUE is the final guard.
INSERT INTO sites (
    handle, owner_id, visibility, default_branch,
    publish_mode, github_repo, web_root, description
)
VALUES (
    @handle,
    @owner_id,
    @visibility,
    @default_branch,
    @publish_mode,
    sqlc.narg(github_repo),
    @web_root,
    @description
)
RETURNING *;

-- name: GetSiteByID :one
-- Control-plane detail load by immutable UUID. Soft-deleted rows are still returned
-- here (the reaper/admin needs them); callers filter on deleted_at as needed.
SELECT * FROM sites WHERE id = @id;

-- name: GetSiteByHandle :one
-- Resolve a *current, live* handle to its full site row (control API + data plane).
-- Excludes soft-deleted sites: a deleted handle 404s. Old handles do NOT match here;
-- redirect handling is GetSiteByRedirect's job.
SELECT * FROM sites
WHERE handle = @handle AND deleted_at IS NULL;

-- name: GetSiteByRedirect :one
-- Resolver fallback: a former handle -> the current site row (data plane issues 301).
-- Joins through handle_redirects; the target site must still be live.
SELECT s.*
FROM handle_redirects r
JOIN sites s ON s.id = r.site_id
WHERE r.old_handle = @old_handle AND s.deleted_at IS NULL;

-- name: GetSiteByGitHubRepo :one
-- GitHub webhook repo -> site mapping. The push payload's "owner/name" resolves the
-- target site so FetchAndUpdate can fast-forward the tracked branch. Only LIVE sites
-- match (a soft-deleted site ignores webhooks); the partial UNIQUE index on
-- github_repo (0001_init) keeps this a single-row lookup.
SELECT * FROM sites
WHERE github_repo = @github_repo AND deleted_at IS NULL;

-- name: ListSitesForUser :many
-- DASHBOARD HOT PATH. Every live site the user can see (owned OR member), newest
-- activity first, with the viewer's effective role. An owner member row is maintained
-- at create time so a single membership join suffices.
SELECT s.id, s.handle, s.owner_id, s.visibility, s.default_branch,
       s.published_commit_sha, s.published_at, s.publish_mode, s.github_repo,
       s.web_root, s.description, s.created_at, s.updated_at, m.role
FROM sites s
JOIN site_members m ON m.site_id = s.id AND m.user_id = @user_id
WHERE s.deleted_at IS NULL
ORDER BY s.updated_at DESC
LIMIT @lim
OFFSET @off;

-- name: HandleIsTaken :one
-- One-shot collision check across live handles, redirects, and reserved words.
-- Returns TRUE if the candidate handle is unavailable for any reason. Columns are
-- table-qualified so the analyzer can resolve `handle` unambiguously across the UNION.
SELECT EXISTS (
    SELECT 1 FROM sites            s WHERE s.handle     = @handle AND s.deleted_at IS NULL
    UNION ALL
    SELECT 1 FROM handle_redirects r WHERE r.old_handle = @handle
    UNION ALL
    SELECT 1 FROM reserved_handles h WHERE h.handle     = @handle
) AS taken;

-- name: RenameHandle :exec
-- Step of the atomic rename (the redirect INSERT is InsertRedirect in the same tx).
UPDATE sites SET handle = @new_handle, updated_at = now()
WHERE id = @id;

-- name: InsertRedirect :exec
-- Record old -> current site mapping. Upsert so a re-freed handle re-points cleanly.
INSERT INTO handle_redirects (old_handle, site_id)
VALUES (@old_handle, @site_id)
ON CONFLICT (old_handle) DO UPDATE SET site_id = EXCLUDED.site_id;

-- name: DeleteRedirect :exec
-- Used on rename-back: drop a stale redirect of THIS site whose old_handle equals the
-- handle we are renaming back to, so the namespace stays consistent.
DELETE FROM handle_redirects WHERE old_handle = @old_handle AND site_id = @site_id;

-- name: ListRedirectsForSite :many
-- Settings UI: all former handles of a site.
SELECT old_handle, site_id, created_at
FROM handle_redirects
WHERE site_id = @site_id
ORDER BY created_at DESC;

-- name: SoftDeleteSite :exec
-- Soft delete (decision #3): stamp deleted_at. Handle stays reserved during the grace
-- window; the on-disk repo retention/reaping is the SiteService's job.
UPDATE sites SET deleted_at = now(), updated_at = now()
WHERE id = @id AND deleted_at IS NULL;

-- name: SetPublished :exec
-- Update the cache pointer at publish time (called AFTER the git ref move succeeds).
UPDATE sites
SET published_commit_sha = @published_commit_sha,
    published_at         = now(),
    updated_at           = now()
WHERE id = @id;

-- name: BumpCacheVersion :one
-- Operator "Clear cache": increment the per-site cache generation and return the
-- NEW value. The data plane folds cache_version into the asset ETag, so a bump
-- changes every asset's ETag at once and forces clients to refetch fresh on their
-- next revalidation (no new commit required). updated_at is intentionally LEFT
-- UNCHANGED: a cache purge is not a content edit and must not reorder the dashboard
-- "recent activity" list (ListSitesForUser orders by updated_at).
UPDATE sites
SET cache_version = cache_version + 1
WHERE id = @id AND deleted_at IS NULL
RETURNING cache_version;

-- name: UpdateSiteSettings :exec
-- Owner-only settings edit (visibility, publish_mode, web_root, description).
UPDATE sites
SET visibility   = @visibility,
    publish_mode = @publish_mode,
    web_root     = @web_root,
    description  = @description,
    updated_at   = now()
WHERE id = @id;

-- name: SetSiteRemote :exec
-- Configure (or clear, when NULL) the GitHub mirror remote for a site.
UPDATE sites SET github_repo = sqlc.narg(github_repo), updated_at = now()
WHERE id = @id;

-- name: ListSitesForReaper :many
-- The soft-delete reaper: sites whose grace window elapsed and still hold a repo.
-- The cutoff is supplied by the caller (now() - grace) so the period stays config-driven.
SELECT id, handle, owner_id, deleted_at
FROM sites
WHERE deleted_at IS NOT NULL AND deleted_at < @cutoff
ORDER BY deleted_at ASC;

-- name: HardDeleteSite :exec
-- Final relational purge after the reaper has bundled + reclaimed the on-disk repo.
DELETE FROM sites WHERE id = @id;

-- name: ListLiveSiteIDs :many
-- The ops gc + consistency check enumerate every LIVE site's id to walk its on-disk
-- repo (gc --auto) and to flag orphan dirs / dangling rows. Soft-deleted sites are
-- excluded — those are the reaper's domain, not gc/consistency.
SELECT id FROM sites WHERE deleted_at IS NULL ORDER BY id;
