// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerPATScopes     = "bearerPAT.Scopes"
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for AuthMode.
const (
	None     AuthMode = "none"
	Oidc     AuthMode = "oidc"
	Password AuthMode = "password"
)

// Defines values for ConflictEnvelopeErrorCode.
const (
	ConflictEnvelopeErrorCodeBranchExists    ConflictEnvelopeErrorCode = "branch_exists"
	ConflictEnvelopeErrorCodeConflict        ConflictEnvelopeErrorCode = "conflict"
	ConflictEnvelopeErrorCodeHandleTaken     ConflictEnvelopeErrorCode = "handle_taken"
	ConflictEnvelopeErrorCodeNothingToCommit ConflictEnvelopeErrorCode = "nothing_to_commit"
)

// Defines values for ErrorEnvelopeErrorCode.
const (
	ErrorEnvelopeErrorCodeBranchExists         ErrorEnvelopeErrorCode = "branch_exists"
	ErrorEnvelopeErrorCodeConflict             ErrorEnvelopeErrorCode = "conflict"
	ErrorEnvelopeErrorCodeForbidden            ErrorEnvelopeErrorCode = "forbidden"
	ErrorEnvelopeErrorCodeHandleTaken          ErrorEnvelopeErrorCode = "handle_taken"
	ErrorEnvelopeErrorCodeInternal             ErrorEnvelopeErrorCode = "internal"
	ErrorEnvelopeErrorCodeNotFound             ErrorEnvelopeErrorCode = "not_found"
	ErrorEnvelopeErrorCodeNothingToCommit      ErrorEnvelopeErrorCode = "nothing_to_commit"
	ErrorEnvelopeErrorCodePublishConflict      ErrorEnvelopeErrorCode = "publish_conflict"
	ErrorEnvelopeErrorCodeQuotaExceeded        ErrorEnvelopeErrorCode = "quota_exceeded"
	ErrorEnvelopeErrorCodeRateLimited          ErrorEnvelopeErrorCode = "rate_limited"
	ErrorEnvelopeErrorCodeTooLarge             ErrorEnvelopeErrorCode = "too_large"
	ErrorEnvelopeErrorCodeUnauthenticated      ErrorEnvelopeErrorCode = "unauthenticated"
	ErrorEnvelopeErrorCodeUnsupportedMediaType ErrorEnvelopeErrorCode = "unsupported_media_type"
	ErrorEnvelopeErrorCodeValidation           ErrorEnvelopeErrorCode = "validation"
)

// Defines values for FileContentEncoding.
const (
	FileContentEncodingBase64 FileContentEncoding = "base64"
	FileContentEncodingUtf8   FileContentEncoding = "utf-8"
)

// Defines values for FileDiffStatus.
const (
	Added    FileDiffStatus = "added"
	Deleted  FileDiffStatus = "deleted"
	Modified FileDiffStatus = "modified"
	Renamed  FileDiffStatus = "renamed"
)

// Defines values for PublishConflictEnvelopeErrorCode.
const (
	PublishConflict PublishConflictEnvelopeErrorCode = "publish_conflict"
)

// Defines values for PublishMode.
const (
	Direct  PublishMode = "direct"
	Request PublishMode = "request"
)

// Defines values for SiteRole.
const (
	SiteRoleEditor SiteRole = "editor"
	SiteRoleOwner  SiteRole = "owner"
	SiteRoleViewer SiteRole = "viewer"
)

// Defines values for SiteVisibility.
const (
	Internal SiteVisibility = "internal"
	Private  SiteVisibility = "private"
	Public   SiteVisibility = "public"
)

// Defines values for TokenScope.
const (
	Publish TokenScope = "publish"
	Read    TokenScope = "read"
	Write   TokenScope = "write"
)

// Defines values for WriteFileRequestEncoding.
const (
	WriteFileRequestEncodingBase64 WriteFileRequestEncoding = "base64"
	WriteFileRequestEncodingUtf8   WriteFileRequestEncoding = "utf-8"
)

// Defines values for WriteSource.
const (
	WriteSourceEditor WriteSource = "editor"
	WriteSourceMcp    WriteSource = "mcp"
	WriteSourceSystem WriteSource = "system"
	WriteSourceUpload WriteSource = "upload"
)

// AuthMode defines model for AuthMode.
type AuthMode string

// Branch defines model for Branch.
type Branch struct {
	// HeadSha Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	HeadSha     Sha         `json:"headSha"`
	IsPublished bool        `json:"isPublished"`
	LastCommit  *CommitInfo `json:"lastCommit,omitempty"`

	// Name Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	Name BranchString `json:"name"`

	// PreviewSubdomain host label fragment: "{handle}" for published, "{handle}--{branch}" otherwise
	PreviewSubdomain string `json:"previewSubdomain"`
}

// BranchString Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
type BranchString = string

// CommitInfo defines model for CommitInfo.
type CommitInfo struct {
	AuthorEmail string    `json:"authorEmail"`
	AuthorName  string    `json:"authorName"`
	Committed   time.Time `json:"committed"`
	Message     string    `json:"message"`
	Parents     *[]string `json:"parents,omitempty"`

	// Sha Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	Sha      Sha         `json:"sha"`
	ShortSha string      `json:"shortSha"`
	Via      WriteSource `json:"via"`
}

// CommitRequest defines model for CommitRequest.
type CommitRequest struct {
	// BaseSha REQUIRED optimistic lock; current branch tip
	BaseSha string  `json:"baseSha"`
	Message *string `json:"message,omitempty"`
}

// ConflictEnvelope defines model for ConflictEnvelope.
type ConflictEnvelope struct {
	Error struct {
		Code ConflictEnvelopeErrorCode `json:"code"`

		// Details Optimistic-lock conflict detail (frozen field names; CANONICAL.md §8).
		Details ConflictError `json:"details"`
		Message string        `json:"message"`
	} `json:"error"`
}

// ConflictEnvelopeErrorCode defines model for ConflictEnvelope.Error.Code.
type ConflictEnvelopeErrorCode string

// ConflictError Optimistic-lock conflict detail (frozen field names; CANONICAL.md §8).
type ConflictError struct {
	// Actual the real current branch tip
	Actual string `json:"actual"`

	// Branch Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	Branch       BranchString `json:"branch"`
	ChangedPaths *[]string    `json:"changedPaths,omitempty"`

	// Expected the baseSha the caller sent
	Expected string `json:"expected"`
}

// CreateSiteRequest defines model for CreateSiteRequest.
type CreateSiteRequest struct {
	Description *string `json:"description,omitempty"`
	GithubRepo  *string `json:"githubRepo"`

	// Handle DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
	Handle      HandleString    `json:"handle"`
	PublishMode *PublishMode    `json:"publishMode,omitempty"`
	Visibility  *SiteVisibility `json:"visibility,omitempty"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	CanCreateSites *bool        `json:"canCreateSites,omitempty"`
	ExpiresAt      *time.Time   `json:"expiresAt"`
	Name           string       `json:"name"`
	Scopes         []TokenScope `json:"scopes"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	CanCreateSites bool               `json:"canCreateSites"`
	CreatedAt      time.Time          `json:"createdAt"`
	ExpiresAt      *time.Time         `json:"expiresAt"`
	Id             openapi_types.UUID `json:"id"`
	LastUsedAt     *time.Time         `json:"lastUsedAt"`
	Name           string             `json:"name"`
	RevokedAt      *time.Time         `json:"revokedAt"`
	Scopes         []TokenScope       `json:"scopes"`

	// Token The plaintext "kotoji_pat_..." secret. Shown ONCE; never returned again.
	Token string `json:"token"`

	// TokenPrefix first 12 chars of the plaintext
	TokenPrefix string `json:"tokenPrefix"`
}

// DiffResult defines model for DiffResult.
type DiffResult struct {
	Files     []FileDiff `json:"files"`
	FromSha   string     `json:"fromSha"`
	ToSha     string     `json:"toSha"`
	Truncated *bool      `json:"truncated,omitempty"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code ErrorEnvelopeErrorCode `json:"code"`

		// Details Code-specific structured detail (e.g. validation field, retry hint).
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ErrorEnvelopeErrorCode defines model for ErrorEnvelope.Error.Code.
type ErrorEnvelopeErrorCode string

// FileContent defines model for FileContent.
type FileContent struct {
	BlobSha string `json:"blobSha"`

	// Content utf-8 text or base64 per encoding
	Content  string              `json:"content"`
	Encoding FileContentEncoding `json:"encoding"`
	IsBinary bool                `json:"isBinary"`
	Path     string              `json:"path"`

	// Sha Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	Sha       Sha   `json:"sha"`
	Size      int64 `json:"size"`
	Truncated *bool `json:"truncated,omitempty"`
}

// FileContentEncoding defines model for FileContent.Encoding.
type FileContentEncoding string

// FileDiff defines model for FileDiff.
type FileDiff struct {
	Additions int  `json:"additions"`
	Deletions int  `json:"deletions"`
	IsBinary  bool `json:"isBinary"`

	// OldPath set on rename
	OldPath *string        `json:"oldPath"`
	Path    string         `json:"path"`
	Status  FileDiffStatus `json:"status"`

	// UnifiedPatch empty if binary or name-status mode
	UnifiedPatch *string `json:"unifiedPatch,omitempty"`
}

// FileDiffStatus defines model for FileDiff.Status.
type FileDiffStatus string

// FileEntry defines model for FileEntry.
type FileEntry struct {
	IsDir bool   `json:"isDir"`
	Mode  string `json:"mode"`
	Name  string `json:"name"`

	// Path repo-relative, forward slashes, no leading /
	Path string `json:"path"`
	Size int64  `json:"size"`
}

// FileListing defines model for FileListing.
type FileListing struct {
	// Branch Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	Branch BranchString `json:"branch"`
	Files  []FileEntry  `json:"files"`

	// Ref Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	Ref Sha `json:"ref"`
}

// GitHubAdminConfig Secret-safe view of the instance GitHub mirror config (admin screen). The token and webhook secret are NEVER returned — only "configured" booleans. Values are the EFFECTIVE config (DB overrides env).
type GitHubAdminConfig struct {
	// Enabled Whether GitHub mirroring is enabled (DB override of env).
	Enabled bool `json:"enabled"`

	// Org GitHub org/owner for created repos (empty if unset).
	Org string `json:"org"`

	// TokenSet True when a push token is configured (DB or env). The token itself is never returned.
	TokenSet bool `json:"tokenSet"`

	// WebhookSecretSet True when a webhook HMAC secret is configured. The secret itself is never returned.
	WebhookSecretSet bool `json:"webhookSecretSet"`
}

// GitHubAdminConfigUpdate Partial update of the instance GitHub mirror config. All fields optional; absent fields are unchanged. The token is write-only (empty/absent keeps the stored one; clearToken removes it).
type GitHubAdminConfigUpdate struct {
	// ClearToken When true, remove the stored token (reverts to the env token if any).
	ClearToken *bool `json:"clearToken,omitempty"`

	Enabled *bool   `json:"enabled,omitempty"`
	Org     *string `json:"org,omitempty"`

	// Token New push PAT/app token (write-only; stored encrypted at rest). Empty/absent keeps the existing token.
	Token *string `json:"token,omitempty"`

	// WebhookSecret New webhook HMAC secret (write-only). Empty/absent keeps the existing secret.
	WebhookSecret *string `json:"webhookSecret,omitempty"`
}

// HandleString DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
type HandleString = string

// InstanceConfig defines model for InstanceConfig.
type InstanceConfig struct {
	AllowedExtensions  []string    `json:"allowedExtensions"`
	AuthMode           AuthMode    `json:"authMode"`
	BaseDomain         string      `json:"baseDomain"`
	DefaultPublishMode PublishMode `json:"defaultPublishMode"`

	// GithubMirrorEnabled True when the instance can mirror to GitHub at all (KOTOJI_GITHUB_MIRROR_ENABLED set AND a push token configured). The GUI keys per-site linking/sync controls off this flag.
	GithubMirrorEnabled bool     `json:"githubMirrorEnabled"`
	HandleMaxLen        int      `json:"handleMaxLen"`
	HandleMinLen        int      `json:"handleMinLen"`
	MaxUploadBytes      int64    `json:"maxUploadBytes"`
	ReservedHandles     []string `json:"reservedHandles"`

	// SetupRequired True only in the first-run state: AUTH_MODE=password AND no env admin password AND no admin password hash stored yet. When true the GUI shows the first-run admin-password setup screen and POST /auth/setup is open. Always false for oidc/none modes.
	SetupRequired    bool   `json:"setupRequired"`
	ZipMaxEntryBytes *int64 `json:"zipMaxEntryBytes,omitempty"`
	ZipMaxFiles      int    `json:"zipMaxFiles"`
	ZipMaxRatio      *int   `json:"zipMaxRatio,omitempty"`
	ZipMaxTotalBytes int64  `json:"zipMaxTotalBytes"`
}

// LogResult defines model for LogResult.
type LogResult struct {
	// Branch Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	Branch  BranchString `json:"branch"`
	Commits []CommitInfo `json:"commits"`

	// NextBefore cursor for the next page; null at end
	NextBefore *string `json:"nextBefore"`
}

// Me defines model for Me.
type Me struct {
	AuthMode AuthMode `json:"authMode"`
	User     User     `json:"user"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Role        SiteRole            `json:"role"`
	UserId      openapi_types.UUID  `json:"userId"`
}

// MirrorResult defines model for MirrorResult.
type MirrorResult struct {
	// Branches Branches the mirror push targeted (typically draft + published).
	Branches []string `json:"branches"`

	// Error Short machine-safe error detail when the push failed; null on success.
	Error *string `json:"error"`

	// Message Human-readable outcome the UI can show (e.g. "GitHub sync failed" or "this site is not linked to a GitHub repository").
	Message string `json:"message"`

	// Ok True when the mirror push succeeded; false on a best-effort failure (still 200).
	Ok bool `json:"ok"`

	// Pushed True when a push was actually attempted and accepted by the remote.
	Pushed bool `json:"pushed"`
}

// PublishConflictEnvelope defines model for PublishConflictEnvelope.
type PublishConflictEnvelope struct {
	Error struct {
		Code    PublishConflictEnvelopeErrorCode `json:"code"`
		Details struct {
			Paths []string `json:"paths"`
		} `json:"details"`
		Message string `json:"message"`
	} `json:"error"`
}

// PublishConflictEnvelopeErrorCode defines model for PublishConflictEnvelope.Error.Code.
type PublishConflictEnvelopeErrorCode string

// PublishMode defines model for PublishMode.
type PublishMode string

// PublishRequest defines model for PublishRequest.
type PublishRequest struct {
	// BaseSha REQUIRED tip of `from` the publish is intended for
	BaseSha string `json:"baseSha"`

	// From Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	From    *BranchString `json:"from,omitempty"`
	Message *string       `json:"message,omitempty"`
}

// PublishResult defines model for PublishResult.
type PublishResult struct {
	// From Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	From BranchString `json:"from"`

	// FromCommit Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	FromCommit Sha `json:"fromCommit"`

	// PublishedCommit Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	PublishedCommit Sha       `json:"publishedCommit"`
	PublishedUrl    *string   `json:"publishedUrl,omitempty"`
	Pushed          bool      `json:"pushed"`
	Warnings        *[]string `json:"warnings,omitempty"`
}

// RollbackRequest defines model for RollbackRequest.
type RollbackRequest struct {
	// BaseSha REQUIRED current branch tip (optimistic lock)
	BaseSha string  `json:"baseSha"`
	Message *string `json:"message,omitempty"`

	// ToSha ancestor commit on this branch whose tree to restore (non-ancestor => 404)
	ToSha string `json:"toSha"`
}

// SetupRequest First-run admin-password setup body (POST /auth/setup).
type SetupRequest struct {
	// Confirm Optional confirmation; when present it must equal password.
	Confirm *string `json:"confirm,omitempty"`

	// Password The admin password to set (min 8 chars; never logged).
	Password string `json:"password"`
}

// Sha Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
type Sha = string

// Site defines model for Site.
type Site struct {
	CreatedAt time.Time `json:"createdAt"`

	// DefaultBranch Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	DefaultBranch BranchString `json:"defaultBranch"`
	Description   string       `json:"description"`
	GithubRepo    *string      `json:"githubRepo"`

	// Handle DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
	Handle HandleString `json:"handle"`

	// HasPublished derived: publishedSha is set
	HasPublished bool               `json:"hasPublished"`
	Id           openapi_types.UUID `json:"id"`
	OwnerId      openapi_types.UUID `json:"ownerId"`
	PublishMode  PublishMode        `json:"publishMode"`
	PublishedAt  *time.Time         `json:"publishedAt"`
	PublishedSha *string            `json:"publishedSha"`
	UpdatedAt    time.Time          `json:"updatedAt"`
	Visibility   SiteVisibility     `json:"visibility"`

	// WebRoot served subdir; empty = repo root (v1)
	WebRoot string `json:"webRoot"`
}

// SiteRole defines model for SiteRole.
type SiteRole string

// SiteSummary defines model for SiteSummary.
type SiteSummary struct {
	// DefaultBranch Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	DefaultBranch *BranchString `json:"defaultBranch,omitempty"`
	Description   *string       `json:"description,omitempty"`

	// Handle DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
	Handle       HandleString       `json:"handle"`
	HasPublished bool               `json:"hasPublished"`
	Id           openapi_types.UUID `json:"id"`
	PublishedAt  *time.Time         `json:"publishedAt"`
	PublishedSha *string            `json:"publishedSha"`
	Role         SiteRole           `json:"role"`
	UpdatedAt    time.Time          `json:"updatedAt"`
	Visibility   SiteVisibility     `json:"visibility"`
}

// SiteVisibility defines model for SiteVisibility.
type SiteVisibility string

// TokenScope defines model for TokenScope.
type TokenScope string

// TokenSummary defines model for TokenSummary.
type TokenSummary struct {
	CanCreateSites bool               `json:"canCreateSites"`
	CreatedAt      time.Time          `json:"createdAt"`
	ExpiresAt      *time.Time         `json:"expiresAt"`
	Id             openapi_types.UUID `json:"id"`
	LastUsedAt     *time.Time         `json:"lastUsedAt"`
	Name           string             `json:"name"`
	RevokedAt      *time.Time         `json:"revokedAt"`
	Scopes         []TokenScope       `json:"scopes"`

	// TokenPrefix first 12 chars of the plaintext
	TokenPrefix string `json:"tokenPrefix"`
}

// UpdateSiteRequest defines model for UpdateSiteRequest.
type UpdateSiteRequest struct {
	Description *string         `json:"description,omitempty"`
	GithubRepo  *string         `json:"githubRepo"`
	PublishMode *PublishMode    `json:"publishMode,omitempty"`
	Visibility  *SiteVisibility `json:"visibility,omitempty"`
	WebRoot     *string         `json:"webRoot,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl      *string             `json:"avatarUrl"`
	CanCreateSites bool                `json:"canCreateSites"`
	DisplayName    string              `json:"displayName"`
	Email          openapi_types.Email `json:"email"`
	Id             openapi_types.UUID  `json:"id"`

	// IsAdmin instance superuser (separate axis from site roles)
	IsAdmin bool `json:"isAdmin"`
}

// WriteFileRequest defines model for WriteFileRequest.
type WriteFileRequest struct {
	// BaseSha REQUIRED commit SHA the edit is based on. Empty/stale => 409 conflict.
	BaseSha  string                    `json:"baseSha"`
	Commit   *bool                     `json:"commit,omitempty"`
	Content  string                    `json:"content"`
	Encoding *WriteFileRequestEncoding `json:"encoding,omitempty"`
	Message  *string                   `json:"message,omitempty"`
	Path     string                    `json:"path"`
}

// WriteFileRequestEncoding defines model for WriteFileRequest.Encoding.
type WriteFileRequestEncoding string

// WriteResult defines model for WriteResult.
type WriteResult struct {
	BlobSha *string `json:"blobSha,omitempty"`

	// Branch Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	Branch       BranchString `json:"branch"`
	BytesWritten *int         `json:"bytesWritten,omitempty"`

	// Commit Full git commit SHA (40 hex SHA-1 or 64 hex SHA-256).
	Commit       Sha    `json:"commit"`
	Committed    bool   `json:"committed"`
	FilesChanged *int   `json:"filesChanged,omitempty"`
	NoOp         *bool  `json:"noOp,omitempty"`
	Path         string `json:"path"`

	// Pushed mirror-push to GitHub succeeded (best-effort)
	Pushed   bool      `json:"pushed"`
	Warnings *[]string `json:"warnings,omitempty"`
}

// WriteSource defines model for WriteSource.
type WriteSource string

// BranchParam Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
type BranchParam = BranchString

// HandleParam DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
type HandleParam = HandleString

// TokenIdParam defines model for TokenId.
type TokenIdParam = openapi_types.UUID

// UserIdParam defines model for UserId.
type UserIdParam = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ConflictEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// TooLarge defines model for TooLarge.
type TooLarge = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorEnvelope

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = ErrorEnvelope

// CreateBranchJSONBody defines parameters for CreateBranch.
type CreateBranchJSONBody struct {
	// From source branch name or SHA
	From string `json:"from"`

	// Name Host-safe branch name. "published"/"draft" reserved; previews are feature-<user>-<slug>.
	Name BranchString `json:"name"`
}

// DeleteFileParams defines parameters for DeleteFile.
type DeleteFileParams struct {
	Path    string  `form:"path" json:"path"`
	BaseSha string  `form:"baseSha" json:"baseSha"`
	Message *string `form:"message,omitempty" json:"message,omitempty"`
}

// ReadFileParams defines parameters for ReadFile.
type ReadFileParams struct {
	Path string  `form:"path" json:"path"`
	Ref  *string `form:"ref,omitempty" json:"ref,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	Dir *string `form:"dir,omitempty" json:"dir,omitempty"`

	// Ref commit SHA; default = branch tip
	Ref       *string `form:"ref,omitempty" json:"ref,omitempty"`
	Recursive *bool   `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// ImportZipMultipartBody defines parameters for ImportZip.
type ImportZipMultipartBody struct {
	// BaseSha REQUIRED unless the branch has no commits yet (initial seed)
	BaseSha *string `json:"baseSha,omitempty"`

	// File the .zip archive
	File    openapi_types.File `json:"file"`
	Message *string            `json:"message,omitempty"`
}

// GetLogParams defines parameters for GetLog.
type GetLogParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before cursor SHA (exclusive)
	Before *string `form:"before,omitempty" json:"before,omitempty"`
	Path   *string `form:"path,omitempty" json:"path,omitempty"`
}

// GetDiffParams defines parameters for GetDiff.
type GetDiffParams struct {
	From string `form:"from" json:"from"`

	// To omit => working tree of from's branch
	To           *string `form:"to,omitempty" json:"to,omitempty"`
	Path         *string `form:"path,omitempty" json:"path,omitempty"`
	ContextLines *int    `form:"contextLines,omitempty" json:"contextLines,omitempty"`
	NameStatus   *bool   `form:"nameStatus,omitempty" json:"nameStatus,omitempty"`
}

// AddMemberJSONBody defines parameters for AddMember.
type AddMemberJSONBody struct {
	Email openapi_types.Email `json:"email"`
	Role  SiteRole            `json:"role"`
}

// UpdateMemberRoleJSONBody defines parameters for UpdateMemberRole.
type UpdateMemberRoleJSONBody struct {
	Role SiteRole `json:"role"`
}

// RenameSiteJSONBody defines parameters for RenameSite.
type RenameSiteJSONBody struct {
	// NewHandle DNS-safe handle. Create-time min length is 3; resolver accepts 1-63. No "--".
	NewHandle HandleString `json:"newHandle"`
}

// GithubWebhookJSONBody defines parameters for GithubWebhook.
type GithubWebhookJSONBody map[string]interface{}

// GithubWebhookParams defines parameters for GithubWebhook.
type GithubWebhookParams struct {
	XHubSignature256 string `json:"X-Hub-Signature-256"`
	XGitHubEvent     string `json:"X-GitHub-Event"`
}

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// AuthLoginParams defines parameters for AuthLogin.
type AuthLoginParams struct {
	// Next Post-login redirect target (validated server-side).
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSiteRequest

// UpdateSiteJSONRequestBody defines body for UpdateSite for application/json ContentType.
type UpdateSiteJSONRequestBody = UpdateSiteRequest

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody CreateBranchJSONBody

// CommitJSONRequestBody defines body for Commit for application/json ContentType.
type CommitJSONRequestBody = CommitRequest

// WriteFileJSONRequestBody defines body for WriteFile for application/json ContentType.
type WriteFileJSONRequestBody = WriteFileRequest

// ImportZipMultipartRequestBody defines body for ImportZip for multipart/form-data ContentType.
type ImportZipMultipartRequestBody ImportZipMultipartBody

// RollbackJSONRequestBody defines body for Rollback for application/json ContentType.
type RollbackJSONRequestBody = RollbackRequest

// AddMemberJSONRequestBody defines body for AddMember for application/json ContentType.
type AddMemberJSONRequestBody AddMemberJSONBody

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody UpdateMemberRoleJSONBody

// PublishJSONRequestBody defines body for Publish for application/json ContentType.
type PublishJSONRequestBody = PublishRequest

// RenameSiteJSONRequestBody defines body for RenameSite for application/json ContentType.
type RenameSiteJSONRequestBody RenameSiteJSONBody

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest

// GithubWebhookJSONRequestBody defines body for GithubWebhook for application/json ContentType.
type GithubWebhookJSONRequestBody GithubWebhookJSONBody

// AuthSetupJSONRequestBody defines body for AuthSetup for application/json ContentType.
type AuthSetupJSONRequestBody = SetupRequest
